from state import AgentState
from langsmith import traceable

# tools
from tools import write_todos
from filesystem import write_file, read_file
from delegate import task

@traceable(name="Strategic_Planner", run_type="chain")
def planner(state: AgentState):
    """
    Milestone 1: Structured Task Planning.
    Creates a dynamic TODO list based on the user's research topic.
    """
    topic = state.get("dataset_item") or "AI in Healthcare Data Privacy"
    print(f"\n[PLANNER] 🧠 Analyzing objective: {topic}")

    # Generate the plan using the write_todos tool
    todos = write_todos(topic)
    
    # Ensure we store the plan in the state for the Executor
    state["todos"] = todos
    print(f"[PLANNER] ✅ Plan created with {len(todos)} sub-tasks.")
    return state

@traceable(name="Task_Executor", run_type="chain")
def executor(state: AgentState):
    """
    Milestone 2, 3 & 4: Execution, Memory, and Delegation.
    This node loops through tasks, uses the file system, and calls sub-agents.
    """
    print("\n[EXECUTOR] 🚀 Starting Autonomous Execution...")
    topic = state.get("dataset_item") or "AI in Healthcare Data Privacy"
    
    # Loop through the tasks defined by the planner
    for todo in state["todos"]:
        if todo["status"] == "pending":
            current_task = todo["task"]
            print(f"\n[EXECUTOR] 🛠️  Current Task: {current_task}")

            # --- MILESTONE 2: Context Offloading (Virtual File System) ---
            if "Search" in current_task or "Research" in current_task:
                # We simulate an intensive search and save it to the virtual disk
                research_data = (
                    f"Research findings for {topic}:\n"
                    "- Major regulations: HIPAA (US), GDPR (EU).\n"
                    "- Technical solutions: Differential Privacy, Federated Learning.\n"
                    "- Risks: Unauthorized access, data breaches, and bias in datasets."
                )
                write_file(state, "research.txt", research_data)
                print(f"[FS] 💾 Saved research data to research.txt")

            # --- MILESTONE 3: Sub-Agent Delegation ---
            elif "Summarize" in current_task:
                # Retrieve the raw research from the Virtual File System
                context = read_file(state, "research.txt")
                
                # Delegate to the Summarizer Sub-Agent
                summary_output = task(context)
                
                # Save the specialist's output back to the Virtual File System
                write_file(state, "summary.txt", summary_output)
                print(f"[FS] 💾 Saved sub-agent summary to summary.txt")

            elif "Analyze" in current_task:
                analysis_results = (
                    f"Privacy Analysis of {topic}:\n"
                    "1. Compliance risk is high due to evolving global laws.\n"
                    "2. Implementation of Zero Trust Architecture is recommended."
                )
                write_file(state, "analysis.txt", analysis_results)
                print(f"[FS] 💾 Saved analysis to analysis.txt")

            # --- MILESTONE 4: Full Synthesis ---
            elif "Write" in current_task or "Report" in current_task:
                # Pull all intermediate "offloaded" data to create the final product
                final_content = f"""
=========================================
        AUTONOMOUS RESEARCH REPORT
=========================================
TOPIC: {topic}

EXECUTIVE SUMMARY:
{read_file(state, 'summary.txt')}

TECHNICAL ANALYSIS:
{read_file(state, 'analysis.txt')}

RESOURCES GATHERED:
{read_file(state, 'research.txt')}

=========================================
Generated by: Deep Cognitive Engine
"""
                write_file(state, "final_report.txt", final_content)
                print(f"[FS] 💾 Final Report generated.")

            # Update the status so the agent knows this task is complete
            todo["status"] = "done"

    return state