from typing import TypedDict, List, Dict, Optional, Any


class AgentState(TypedDict):
    """
    Central shared state for the LangGraph agent.
    """
    # Original user task
    task: str

    # Conversation / reasoning messages
    messages: List[Any]

    # TODO list generated by planner (Milestone-1)
    todos: List[str]

    # Currently executing TODO
    current_todo: Optional[str]

    # Final synthesized output
    final_output: str

    # Virtual File System (Milestone-2)
    files: Dict[str, str]


def create_initial_state(task: str = "") -> AgentState:
    """
    Create and return the initial agent state.
    """
    return {
        "task": task,
        "messages": [],
        "todos": [],
        "current_todo": None,
        "final_output": "",
        "files": {}   # 👈 Milestone-2 VFS memory
    }

